### ISSUE TITLE
Cannot recover for error

### ISSUE THREAD

**Issue by atd** [nfroidure/StreamQueue#7]
```js
gulp.src('./src/js/**/*.js')
  .pipe(ngFilesort())
  .on('error', function(er) {console.error(er);} );
```

Prints the error and recovers from it, as expected.

However, wrapping up in `streamqueue` prevents the script from recovering from the error. 

Both:

```js
streamqueue({ objectMode: true },
  gulp.src('./src/js/**/*.js')
    .pipe(ngFilesort())
    .on('error', function(er) {console.error(er);} )
);
```
and
```js
streamqueue({ objectMode: true },
  gulp.src('./src/js/**/*.js')
    .pipe(ngFilesort())
).on('error', function(er) {console.error(er);} );
``` 
fail with

```
events.js:72
        throw er; // Unhandled 'error' event    
```

**Comment by nfroidure** [comment]
You need https://www.npmjs.com/package/gulp-plumber ;)

**Comment by atd** [comment]
That's the first thing I tried, but it didn't work :pensive:

**Comment by nfroidure** [comment]
Won't be able to help more without stack trace but except if there really is a bug in streamqueue, i assume the error come from the gulp.src stream so it is normal that it isn't cought up in the above examples.

It it isn't the case, please create a failing test/project setup in order for me to investigate and reopen the issue.

**Comment by atd** [comment]
@nfroidure thank you for your follow up with this

The error comes from `ngFilesort()` when there is a file with a syntax error.

Could you please point me how I should properly catch the error? I will create a failing test with it

**Comment by nfroidure** [comment]
Since StreamQueue reemits errors whenever you already listen to them on the streams you provide to him, the following still throws and it is normal:

```js
streamqueue({ objectMode: true },
  gulp.src('./src/js/**/*.js')
    .pipe(ngFilesort())
    .on('error', function(er) {console.error(er);} );
);
```
We could however allow to avoid reemiting with such an option https://github.com/nfroidure/plexer#optionsreemiterrors .

In the other hand, the following should not throw since streamqueue listen to errors on the given stream https://github.com/nfroidure/StreamQueue/blob/master/src/index.js#L92 :
```js
streamqueue({ objectMode: true },
  gulp.src('./src/js/**/*.js')
    .pipe(ngFilesort())
).on('error', function(er) {console.error(er);} );
```

So if you have a use case when the above fails (and the error doesn't come from the gulp.src stream and ngFileSort doesn't fire error events synchronously), just add it the and PR the repo https://github.com/nfroidure/StreamQueue/blob/master/tests/index.mocha.js.

**Comment by atd** [comment]
The last example does not catch the error for me.

When I have some time I will investigate ngFileSort error fire and add the test if appropriate.

**Comment by nfroidure** [comment]
Also, check your StreamQueue version, provide your NodeJS version and just paste the full stack trace of the error in the meanwhile.

**Comment by atd** [comment]
```
$ npm list streamqueue
└── streamqueue@0.1.3 
```

```
$ node -v
v0.10.38
```

`console.log(error)` output:
```
{ [Error: Error in parsing: "test.js", Line 1: Unexpected identifier]
  message: 'Error in parsing: "test.js", Line 1: Unexpected identifier',
  showStack: true,
  showProperties: true,
  plugin: 'gulp-angular-filesort',
  __safety: { toString: [Function] } }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Error in parsing: "test.js", Line 1: Unexpected identifier
```

`console.log(error.stack)` output:
`undefined`
