### ISSUE TITLE
How to exit from StreamQueue with a calback?

### ISSUE THREAD

**Issue by georgschlenkhoff** [nfroidure/StreamQueue#8]
I am using streamqueue like this in a `gulpfile.js` in my project: 

```
gulp.task('scripts', function() {
  return streamqueue({objectMode: true},
    gulp
      .src('app/js/*.js')
      .pipe(jshint())
      .pipe(concat('app_without_template.js'))
      .pipe(header('(function () { \n"use strict";\n\n'))
      .pipe(footer('\n}());')),
    gulp
      .src('app/!(index)**/*.html')
      .pipe(templateCache({module: 'myapp'}))
  )
    .pipe(concat('app.js'))
    .pipe(gulp.dest('.tmp'));
});
```

That works fine. HOWEVER, when another task depends on `scripts` task, the other task will fail, because the streamqueue process has not finished.

I tried to do some fancy `.on('close', function () {done();}` at the end of streamqueue, but with no success.

Anyone knows how to send signal to another task, that streamqueue has finished its work?

**Comment by nfroidure** [comment]
streamqueue normally ends when every streams you given end. If it doesn't, it is probably because some of them doesn't.

Try to find which one by adding a .on('end', console.log.bind(console, 'PluginX ended') for all of them and you'll get the answer.

If they all end, feel free to reopen and give the minimum amount of code to reproduce the behavior.
